//ｂａｎｎｅｒ
BANNER_INFO_TITLE_NUM = 50;
BANNER_INFO_INTRODUCE_NUM = 100;
URL_NOT_NULL = "访问链接不能为空";
DATA_ERROR = "数据错误";
BANNER_SELECT_NEWS = "请选择一个有效的新闻";
BANEER_SELECT_EVA = "请选择一个有效的广告sssssss";
BANNER_TEXT_OUT_NUMBER = "字数超出限制";
BANNER_TITLE_NOT_NULL = "标题不能为空";
BANNER_INTRODUCE_NOT_NULL = "简介不能为空";
BANNER_LINK_NOT_NULL = "详情页链接不能为空";

BANNER_INFO_ISSETTING = "信息已存在";
BANNER_UPDATE_ERROR = "更新失败";
BANNER_ADD_ERROR = "添加失败";
BANNER_DELETE_SUCCESS = "删除成功";
BANNER_DELETE_ERROR = "删除失败";
BANNER_DELETE_LAST_ONE = "最后一条信息不能删除";
BANNER_IMAGE_NOT_NULL = "图片不能为空";